### ISSUE TITLE
OpenSearch Notifications plugin

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/notifications#181]
Effective notifications are critical parts of OpenSearch so that our customers can rapidly identify the issues and mitigate them. Notification’s applicability spans beyond the alerting plugins. Notifications must be accessible from any relevant plugin.  For example, customers prefer to be notified when a scheduled job in reporting, roll-ups, rollover and delete actions in index state management is completed. Operators, still however need the ability to track all the notifications generated by various plugins. The current plugins and visualization needs to be refactored to enable central management of notifications.

## Epic breakdown
- Common utils migration #105
- Add support for savings notification events #25
- List supported features API #133
- Notification sending pre-checks & audits #54
- Implement _stats API #74
- Remove legacy code #78
- List channel for a feature(other plugin) #138
- improve Unit tests #98
- Integration tests for channels #149
- SNS channel #158
- SES channel #167
- Documentation #117

**Comment by dblock** [comment]
> we moved this release to Opensearch 1.2 due to pending testing on the matrix of access control roles & tenants.
> will post more details here on an issue to follow

Does this mean we need to remove it from the 1.1 manifest? I opened https://github.com/opensearch-project/opensearch-build/issues/343. Isn't some other plugin depending on it?

**Comment by anirudha** [comment]
Yes. This is for 1.2 release

**Comment by dblock** [comment]
Can we close this now?
