### ISSUE TITLE
Support aggregation queries for date histogram in UI

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/notifications#187]
**Is your feature request related to a problem? Please describe.**
Frontend UI has a date histogram to display count over time aggregated by these fields:
```
status_list.config_type
event_source.feature
event_source.severity
status_list.delivery_status.status_code (200 vs others)
status_list.config_name (top 10 only)
```
Needs an API in backend to support these

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qreshi** [comment]
Closing this issue as the event functionality is no longer present in the plugin.
