### ISSUE TITLE
Support backend role filtering for notification channels

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#220]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add backend roles to the notification channels model. Then the user object can be used to find channels with the same backend roles.

**Describe alternatives you've considered**
N/A

**Additional context**
The Alerting plugin allows for customer to associate backend roles to destinations. [More context](convertGetNotificationConfigResponseToGetDestinationsResponse)

**Comment by zhongnansu** [comment]
@lezzago I believe notification has backend role filtering supported. See ref below. Tho I didn't wrote this code, I assume the logic is to retrieve info like `tenant` and `backendRoles` from user context?
https://github.com/opensearch-project/notifications/blob/02cfe52e4b1e4395877574ec6f27fffa33432782/notifications/src/main/config/notifications.yml#L55
https://github.com/opensearch-project/notifications/blob/develop/notifications/src/main/kotlin/org/opensearch/notifications/model/DocMetadata.kt#L48

**Comment by lezzago** [comment]
Thanks, that is good then
