### ISSUE TITLE
[BUG] Support Email credentials from Alerting

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#230]
**Describe the bug**
Notification does not support retrieving email username and password from keystore using the Alerting plugin's path that is shown [here](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/settings/DestinationSettings.kt#L53-L65).

**To Reproduce**
N/A

**Expected behavior**
Support retrieving credentials from there as a fallback

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**

**Comment by zhongnansu** [comment]
This task has the following change to make
- [ ] 1. In common-utls, update notification SmtpAccount model to have credentials
- [ ] 2. In notification SPI:
  - [ ] 2.1 update destination model and add logic to EmailClient which loads the credentials when setting up client to send mail
  - [ ] 2.2 Add username and password as plugin setting.
- [ ] 3. Notificaiton main project: Update the send notification transport action handler to parse and pass the credentials
