### ISSUE TITLE
[Epic] Issues during integration from source plugins

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/notifications#231]
this is an epic for all issues reported from other source plugin(Alerting, Reporting, etc) during the development of integration to notification 

- [x] #230 
- [x] #245 
- [x] #247
- [x] #246
- [x] #238 
- [x] #233 
- [x] #219 
- [x] #226 
- [x] #220
- [x] #232 

more issues
- [x] #256 
- [x] #255 
- [x] #253 
- [x] #262

**Comment by qreshi** [comment]
Closing this issue since Alerting and ISM have successfully integrated with Notifications.
