### ISSUE TITLE
[BUG] No support for http urls in notification channels

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#232]
**Describe the bug**
The notification plugin does not support "http" urls for the notification channels like Webhook. The alerting plugin already supports this and breaks functionality when integrating with notification plugin.

**To Reproduce**
N/A

**Expected behavior**
The notification plugin should support "http" urls.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by zhongnansu** [comment]
I thought the original idea is to not support `http`, only support `https`. As code [here](https://github.com/opensearch-project/common-utils/blob/4ef189df7708ace7bf91867bbe6b30fd3bf98a9c/src/main/kotlin/org/opensearch/commons/utils/ValidationHelpers.kt#L38) suggests

**Comment by lezzago** [comment]
Currently Alerting plugin supports `http`, so this can break integration for some users
