### ISSUE TITLE
Add notifications roles to security plugin for cluster permissions

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/notifications#243]
1. Need to send PR to add roles to security and dashboards security plugin, cluster permissions list:
```
    "cluster:admin/opensearch/notifications/configs/create",
    "cluster:admin/opensearch/notifications/configs/delete",
    "cluster:admin/opensearch/notifications/configs/get",
    "cluster:admin/opensearch/notifications/configs/update",
    "cluster:admin/opensearch/notifications/events/get",
    "cluster:admin/opensearch/notifications/feature/channels/get",
    "cluster:admin/opensearch/notifications/feature/send",
    "cluster:admin/opensearch/notifications/features",
    "cluster:admin/opensearch/notifications/send"
```
2. Need to send PR to dashboards security plugin
---
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qreshi** [comment]
Default roles were added in https://github.com/opensearch-project/security/pull/1847
