### ISSUE TITLE
[BUG] Uncaught exception in sendNotification

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/notifications#246]
**Describe the bug**
When calling send notification w/ a non-existent channel it throws an uncaught exception in the dispatcher and then further calls don't work.

**Comment by zhongnansu** [comment]
@dbbaughe is it same as this issue? It's closed without any fix, if neccessay we can re-open

**Comment by dbbaughe** [comment]
@zhongnansu I believe I was on the latest of common-utils and notifications, you can give it a quick test yourself and double check if you experience the same issue.

**Comment by dbbaughe** [comment]
I believe we can close this one; seemed to have been an issue w/ the different ways we were handling exceptions in ISM and Notification in coroutines. Can adjust in ISM.
