### ISSUE TITLE
[BUG] Support search query on Notification Configs for Alerting support

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#255]
**Describe the bug**
Support an API to query the notification config through a search query. Currently the Alerting plugin has support for searching emailAccounts and emailGroups through a search query in the following APIs: [SearchEmailGroup](https://opensearch.org/docs/monitoring-plugins/alerting/api/#search-email-group) and [SearchEmailAccount](https://opensearch.org/docs/monitoring-plugins/alerting/api/#search-email-account). Without the support of this API, the Alerting plugin's API can only support basic queries and will break when users use complicated search queries.

**To Reproduce**
N/A

**Expected behavior**
Have support for a search query as a parameter to query the index.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by akbhatta** [comment]
Can you please add specifics on what extra fields needs to be queried apart from what is available in NotificationConfigRestHandler.kt:L150. below is comment copied for your reference

```
            /**
             * Get list of notification configs
             * Request URL: GET [REQUEST_URL?config_id=id] or [REQUEST_URL?<query_params>]
             * <query_params> ->
             *     config_id_list=id1,id2,id3
             *     from_index=20
             *     max_items=10
             *     sort_order=asc
             *     sort_field=config_type
             *     last_updated_time_ms=from_time..to_time
             *     created_time_ms=from_time..to_time
             *     is_enabled=true
             *     config_type=slack,chime
             *     feature_list=alerting,reports
             *     name=test
             *     description=sample
             *     email.email_account_id=abc,xyz
             *     email.email_group_id_list=abc,xyz
             *     smtp_account.method=ssl
             *     slack.url=domain
             *     chime.url=domain
             *     webhook.url=domain
             *     email.recipient_list=abc,xyz
             *     email_group.recipient_list=abc,xyz
             *     smtp_account.host=domain
             *     smtp_account.from_address=abc,xyz
             *     smtp_account.recipient_list=abc,xyz
             *     query=search all above fields
             * Request body: Ref [org.opensearch.commons.notifications.action.GetNotificationConfigRequest]
             * Response body: [org.opensearch.commons.notifications.action.GetNotificationConfigResponse]
             */
```

**Comment by lezzago** [comment]
The problem is not the fields but how the user creates the query. For example, they can write a query where they want the count of all the email accounts such that the response would just be the number of email accounts and doesn't print out the email accounts. This count can be extracted from the `totalHits` field, but this is just an example of a user writing weird query that would work with the alerting plugin, but not the notification plugin.

Plus the user can write [aggregation queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html).

**Comment by akbhatta** [comment]
For the FGAC support, the configuration needs to be secure. Any idea on supporting free-form query while supporting FGAC?

**Comment by lezzago** [comment]
Most general cases of the SearchEmailGroup and SearchEmailAccount APIs can be supported with the GetNotificationConfig API. Its just a problem with the more complicated queries and edge cases.

**Comment by lezzago** [comment]
> For the FGAC support, the configuration needs to be secure. Any idea on supporting free-form query while supporting FGAC?

If we add a wrapper filter query on top of the user's query, it will ensure only those type of data will be exposed. This is already been done and proven in the Security plugin.

**Comment by lezzago** [comment]
@elfisher, if there is no support for the API from Notification plugin, the API from Alerting will then only be able to support basic queries to search email accounts and email groups. This would support most cases for users, but not the complicated queries.

This is a backwards compatibility support breaking change.

**Comment by anirudha** [comment]
APIs: SearchEmailGroup and SearchEmailAccount
The goal of these api's are to search email groups and email accounts; which is currently possible.

These API's don't have documented behaviors which are in line is our description of breaking changes w.r.t complicated queries and aggregations. hence they are not breaking backward compatibility.

The notifications plugin will provide full search capabilities on the [data model](https://github.com/opensearch-project/notifications/issues/255#issuecomment-892207715) for email-group and email-account. stats, aggregations are other may be side-effects of original implementation but are features as described in the original spec. 

With current implementation alerting plugins can support the existing api usecases. if an aggregation or stats query or any non-supported query is entered; we need to provide a clear error message stating why it is unsupported.

**Comment by lezzago** [comment]
This should not be closed

**Comment by lezzago** [comment]
Backend role filtering is not supported right now on these 2 APIs from alerting also

**Comment by lezzago** [comment]
Here is an example of an aggregation query running on the `searchEmailGroup` API with dummy data

request:
```
POST _plugins/_alerting/destinations/email_groups/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      }
    }
  },
  "aggs": {
    "first-agg": {
      "terms": {
        "field" : "email_group.name.keyword"
      }
    }
  }
}
```

response:
```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : ".opendistro-alerting-config",
        "_type" : "_doc",
        "_id" : "8Kx1dHsBTLSJ1jKkTVsH",
        "_seq_no" : 116,
        "_primary_term" : 91,
        "_score" : 1.0,
        "_source" : {
          "schema_version" : 3,
          "name" : "example_email_group_for_search",
          "emails" : [
            {
              "email" : "example3@email.com"
            }
          ]
        }
      },
      {
        "_index" : ".opendistro-alerting-config",
        "_type" : "_doc",
        "_id" : "9ax6dHsBTLSJ1jKkJFtT",
        "_seq_no" : 117,
        "_primary_term" : 91,
        "_score" : 1.0,
        "_source" : {
          "schema_version" : 3,
          "name" : "example_email_group_for_search2",
          "emails" : [
            {
              "email" : "example_search2@email.com"
            }
          ]
        }
      }
    ]
  },
  "aggregations" : {
    "first-agg" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "example_email_group_for_search",
          "doc_count" : 1
        },
        {
          "key" : "example_email_group_for_search2",
          "doc_count" : 1
        }
      ]
    }
  }
}
```

**Comment by akbhatta** [comment]
#340 keeps the schema format same as Alerting.
