### ISSUE TITLE
Notifications plugin has no branches/tags

### ISSUE THREAD

**Issue by mch2** [opensearch-project/notifications#259]
https://github.com/opensearch-project/notifications is not following a branch/tag strategy similar to other repos.

There is no way to know which ref was included with the 1.0 release.

As we move to a centralized build where components are checked out and built, it is critical we know which versions are to be included for a particular bundle version. Example of how this will be recorded [here](https://github.com/opensearch-project/opensearch-build/pull/141/files#diff-fabc276b3604f4208e6030e760f0bdf834d81a3cc166546c18ec2da3facc2bb4).

**Comment by joshuali925** [comment]
Hi @mch2, Notifications was not included with the 1.0 release. This plugin is still in development and not ready to be used by external users. Code is available in `develop` branch only. Could you let us know if further actions are needed currently? thanks

**Comment by zhongnansu** [comment]
#216 We have issues for this. But like Josh mentioned, notification is still under development

**Comment by dblock** [comment]
Can someone transfer this issue into notifications? I don't have permissions :(
