### ISSUE TITLE
[BUG] Support for Alerting destination permissions 

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#261]
**Describe the bug**
For current users that use security, they have already configured their users to have the following permissions: `cluster:admin/opendistro/alerting/destination/get`
`cluster:admin/opendistro/alerting/destination/email_account/get`
`cluster:admin/opendistro/alerting/destination/email_group/get`
`cluster:admin/opendistro/alerting/destination/write`
`cluster:admin/opendistro/alerting/destination/email_account/write`
`cluster:admin/opendistro/alerting/destination/email_group/write`
`cluster:admin/opendistro/alerting/destination/email_account/search`
`cluster:admin/opendistro/alerting/destination/email_group/search`
`cluster:admin/opendistro/alerting/destination/delete`
`cluster:admin/opendistro/alerting/destination/email_account/delete`
`cluster:admin/opendistro/alerting/destination/email_group/delete`.

We need to ensure that once these users upgrade, the can still use these permissions for the channels/configs related to alerting. Otherwise their experience will be broken and need to reconfigure their user permissions.

**Expected behavior**
Check for those permissions if the api call is coming from the Alerting plugin to allow the users to perform those actions.

**Comment by akbhatta** [comment]
I believe this should be raised to Security plugin because security plugin handles FGAC permissions (transport API permissions)

**Comment by lezzago** [comment]
This does not need to be done in the security plugin. You can wrap the execution call from the rest handler to the transport action to see if it fails due to security permissions and then try the call again by using the other cluster permissions.

For example in [here](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteDestinationAction.kt#L81-L83), it would look like:

```
try {
        return RestChannelConsumer { channel ->
                    client.execute(DeleteDestinationAction.INSTANCE, deleteDestinationRequest, RestToXContentListener(channel))
        }
} catch (e: SecurityException) {
        return RestChannelConsumer { channel ->
                    client.execute(DeleteDestinationOtherPermissionAction.INSTANCE, deleteDestinationRequest, RestToXContentListener(channel))
        }
}
```

On top of this you can check if the call is coming from the alerting plugin.

**Comment by lezzago** [comment]
@elfisher, please take a look at this if it is needed. Without the support for these permissions, the user needs to reconfigure their cluster permissions to use the Alerting plugin for notifications.

**Comment by elfisher** [comment]
@dblock would like to get your take on this too.

One of the goals with 1.x of OpenSearch is to minimize any backwards compatibility breaking changes. The project is following [SemVer](https://semver.org/). Per `#8` in the SemVer spec, breaking changes would require an increment to the project's major version. I would recommend going with the approach that does not introduce a breaking backwards compatibility change in 1.x. If there is a good reason to introduce a breaking change, let's track that as an issue and queue it up for 2.x. 

Is there a concern with the suggestion to wrap the execution call from the rest handler?

**Comment by vrozov** [comment]
I see several issues with the proposed solutions:

- for a new installation users will assume that notifications permission are separate from alerting permissions and may create two separate roles `manage_notifications` and `manage_alerts` with role mappings that grants user "a" `manage_notification` role and user "b" `manage_alerts` role. The problem is that user "b" would be able to delete notifications due to the call to `client.execute(DeleteDestinationOtherPermissionAction.INSTANCE, deleteDestinationRequest, RestToXContentListener(channel))`.
- It is not clear where and how `DeleteDestinationOtherPermissionAction.INSTANCE` is defined. Is it defined in the alerting plugin? In this case, how notification plugin can invoke it? Is it defined in the notification plugin and share name with the alerting plugin? I don't think this is allowed.

**Comment by vrozov** [comment]
> I believe this should be raised to Security plugin because security plugin handles transport API permissions

It is transparent to the security plugin as it only sees action names, but does not have any insight on the action meaning.

**Comment by lezzago** [comment]
A new proposed solution is to provide customers an upgrade script that will update all of user roles that have alerting permissions to also have the required notification permissions to prevent this from breaking the existing users' experience.

This should be the simplest solution as it will also not require any code changes

**Comment by dbbaughe** [comment]
@lezzago what happens for users that upgrade without running the script? It just breaks? Providing a script is nice, but then it still needs to be called out that a breaking change is introduced and here is an upgrade script to use.

**Comment by zengyan-amazon** [comment]
the person needs to have security admin role to execute the migration script, otherwise the script will fail. especially for users who doesn't grant programmatic access to security APIs (e.g. they only use SAML/OIDC for admins), they will need to create a new role/user to execute the migration script

**Comment by skkosuri-amzn** [comment]
Introducing an upgrade script (run by super-admin) might help to address future backward compactability usecases also.

**Comment by akbhatta** [comment]
Closing as the solution is added to alerting plugin
