### ISSUE TITLE
[BUG] Backwards compatibility breaking with Alerting backend role filter

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#296]
**Describe the bug**
Notification plugin does not enable/disable the backend role filter using the alerting setting found [here](https://opensearch.org/docs/monitoring-plugins/alerting/security/#advanced-limit-access-by-backend-role) and that breaks backwards compatibility. Because there was the migration from ODFE to Opensearch, there are 2 settings that Notification needs to support: `plugins.alerting.filter_by_backend_roles` and `opendistro.alerting.filter_by_backend_roles`.

**To Reproduce**
Use this: https://opensearch.org/docs/monitoring-plugins/alerting/security/#advanced-limit-access-by-backend-role to change the setting

**Expected behavior**
Can enable/disable the backend role filter using the alerting setting: `plugins.alerting.filter_by_backend_roles` and `opendistro.alerting.filter_by_backend_roles`

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by akbhatta** [comment]
To maintain backward compatibility now the notification plugin uses Alerting plugin's setting to enable RBAC. support for other filtering (including tenant) is removed.
