### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/notifications#301]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by akbhatta** [comment]
Since Notification plugin is not yet released, I believe backwards compatibility tests are not required. Please re-open if required.

**Comment by praveensameneni** [comment]
We are releasing notifications in 2.0, closing this for 1.3 and open in 2.0

**Comment by dblock** [comment]
It will be required for 2.0 when the plugin releases!

**Comment by praveensameneni** [comment]
Notification plugin will be released in 2.0 and not in previous releases. Can you elaborate what should be the scope of testing.

**Comment by praveensameneni** [comment]
Closing the issue as Notification plugin will be released in 2.0. We will add BWC tests for 2.1
