### ISSUE TITLE
Improve gradle build to build/update notifiations-core artifact on the fly

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/notifications#327]
**Is your feature request related to a problem? Please describe.**

Currently if any changes is made to `notification-core`, one has to build the `notification-core plugin` artifcact and add the zip to the `notification/src/test/resources/notifications-core` so that integration tests in `notification` plugin can take the latest core code. 

This is additional effort when commiting code, and it can and should be optimized.

Consider the following points when optimize
1. make the notification plugin build depends on `notifciation-core` build
2. Automatically move the core artifact to notification test resources, before the notifiations plugin build starts
3. Optional: furthermore, what we can do, is to remove the test resources, or make it optional. Instead, during the `integTest` task of `notifiations`, it should build an artifact on the fly and installed to the test cluster.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qreshi** [comment]
Closing this as it was done in https://github.com/opensearch-project/notifications/issues/415
