### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#332]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.2.0`.

### CI/CD

- [ ] Increment version on main to `1.2.0.0`.
- [ ] Ensure working and passing CI.
- [ ] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [ ] Branch and build from a `1.2` branch.
- [ ] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).
- [ ] Feature complete, pencils down.
- [ ] Fix bugs that target this release.

### Release

- [ ] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [ ] Gather, review and publish release notes.
- [ ] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [ ] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [ ] Conduct a postmortem, and publish its results.

**Comment by peternied** [comment]
@opensearch-project/notifications Could we assign someone to this issue to drive the 1.2 release?

**Comment by zhongnansu** [comment]
@dblock @peternied @anirudha 
Notification will not be released in Opensearch `1.2`

**Comment by peternied** [comment]
@zhongnansu Our guidance for plugins that do not have additional features is to follow the release checklist so that component versions are all aligned.

**Comment by zhongnansu** [comment]
> @zhongnansu Our guidance for plugins that do not have additional features is to follow the release checklist so that component versions are all aligned.

@peternied  Notification is a new plugin that still under development, it has never been released before. So I don't think a "release checklist" applies here. We'll bump the versions for development purpose. Can we close this issue and remove it from the parant issue as well?

**Comment by peternied** [comment]
@zhongnansu You are absolutely correct, yup, you can just close this out.

**Comment by dblock** [comment]
Was this accidentally reopened?
