### ISSUE TITLE
Use SNAPSHOT artifacts from maven for dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#365]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/45, use SNAPSHOT Maven dependencies from [aws.oss.sonatype.org](https://aws.oss.sonatype.org/content/repositories/snapshots). See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#building-within-the-opensearch-build-system for details.

https://github.com/opensearch-project/notifications/blob/main/.github/workflows/notifications-test-and-build-workflow.yml#L44

**Comment by dblock** [comment]
@qreshi Is this done? Since notiications doesn't ship in 1.3.0 I'll label this 2.0 for now.

**Comment by qreshi** [comment]
@dblock Yeah, OpenSearch and CommonUtils are pulled from snapshot during build and have been removed from the GitHub Action so we can close this out.
