### ISSUE TITLE
Add auto backport functionality to backport PRs for releases

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/notifications#369]
Coming from meta issue [opensearch-project/opensearch-plugins#108](https://github.com/opensearch-project/opensearch-plugins/issues/108):

- [x] Add auto-backport PR creation Github action to make sure all the PRs are backported for a particular release. 
- [x] Add auto-delete for merged auto-backport PRs to clean up the branches created during auto-backport.
- [x] Add documentation for the same.

Related documentation: https://github.com/opensearch-project/opensearch-plugins/blob/main/BACKPORT.md

**Comment by praveensameneni** [comment]
Closing this issue as notification plugin is planned for 2.0 release, will re-open for 2.0

**Comment by VachaShah** [comment]
@praveensameneni, we can keep this issue open. I will add in the meta issue that notifications is not for 1.3. Does that work?

**Comment by praveensameneni** [comment]
Yes, that will work.

**Comment by VachaShah** [comment]
> Yes, that will work.

Thank you! I added a note for it in the meta issue.

**Comment by qreshi** [comment]
@VachaShah We added the backport workflow but need to add the secrets. I don't think I have full access to the repo settings. Can you have someone help with that?

**Comment by VachaShah** [comment]
@qreshi I added the secrets.

**Comment by qreshi** [comment]
@VachaShah Thanks! Is there any way to dry-run test the workflow? Otherwise, we can close the issue and re-open it if it doesn't work when we use it.

**Comment by qreshi** [comment]
I confirmed the backport workflow works. Thanks @VachaShah, closing the issue.
