### ISSUE TITLE
Remove jcenter repository

### ISSUE THREAD

**Issue by mch2** [opensearch-project/notifications#373]
## Description
JCenter has been turned off and should be removed as a referenced repository.

Please Remove any direct dependency on jcenter() within a repositories block in gradle files.

Related: https://github.com/opensearch-project/opensearch-build/issues/1456

**Comment by zhongnansu** [comment]
We haven't released this project, the ownership of this project is during transition. Once that's complete,  we'll get to all the release campaigns together.

**Comment by zhongnansu** [comment]
> @opensearch-project/notifications can this be triaged and prioritized?

We haven't released this project, the ownership of this project is during transition. Once that's complete,  we'll get to all the release campaigns together.

**Comment by lezzago** [comment]
Currently the project is not released and will be modified a bit. When that goes on, we will ensure to remove `jcenter()`.
