### ISSUE TITLE
Add refresh policy to CRUD APIs

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/notifications#381]
**Is your feature request related to a problem? Please describe.**
Notification integration tests are flaky as sometimes operations are done to create/delete and then retrieve Notification configs which don't alway reflect the changed state.

**Describe the solution you'd like**
The CRUD API for Notification at times may be used to change state of the underlying documents and then be retrieved with a short turnaround time to retrieve the changed state. Allowing to pass in `?refresh=true` to ensure refreshes on the Notification config index after such operations could be useful for this.

**Describe alternatives you've considered**
For the flaky tests in particular we could add a longer `Thread.sleep` (which are already present) but this is hacky and should be avoided when an internal mechanism exists.

**Additional context**

**Comment by Hailong-am** [comment]
duplicate with https://github.com/opensearch-project/notifications/issues/790, will track by #790
