### ISSUE TITLE
Replace checked-in ZIPs with dynamic dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#415]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1750, replace checked in ZIP(s) with dynamic dependencies.

```
./notifications/notifications/notifications/src/test/resources/notifications-core/opensearch-notifications-core-2.0.0.0-SNAPSHOT.zip
```

**Comment by dblock** [comment]
@dbbaughe Can you please help find an owner for this, it's part of 2.0 campaigns.

**Comment by dbbaughe** [comment]
@dblock Don't have bandwidth this week - added Mohammad who is leading this, he should be able to help find someone.

**Comment by qreshi** [comment]
Since `notifications-core` is a local subproject, I'm guessing we'll want to use the locally built zip and not an uploaded artifact since it might not reflect local changes?

**Comment by elfisher** [comment]
Is this required for 2.0?

**Comment by qreshi** [comment]
It's a 2.0 campaign but it's build specific so if we've missed the window on it, it shouldn't be a big deal.

**Comment by sbcd90** [comment]
this issue is fixed now.closing this.
