### ISSUE TITLE
[FEATURE] Automated security tests

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/notifications#418]
**Is your feature request related to a problem?**
It seems like there are no automated security tests for the plugin, changes like this would need a mechanism to be validated automatically - https://github.com/opensearch-project/notifications/pull/416

**What solution would you like?**
Run test cluster with security plugin and execute the tests to verify security behavior of the plugin

**Comment by qreshi** [comment]
Closing this in favor of https://github.com/opensearch-project/notifications/issues/258
