### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch distribution

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#433]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

**Comment by peterzhuamazon** [comment]
Their PR, check failed, not merged:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/185

**Comment by peterzhuamazon** [comment]
Test merged.

**Comment by qreshi** [comment]
@peterzhuamazon Just to confirm, even before this issue was created, we were already running the *backend* integration tests that we already have for this repo correct?

The issue linked above is for the frontend tests which were not in place.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon Just to confirm, even before this issue was created, we were already running the **backend** integration tests that we already have for this repo against the distribution correct?
> 
> The issue linked above is for the frontend tests which were not in place.

Merged in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/185.
Please consider fixing the issues there.

Thanks.

**Comment by qreshi** [comment]
My question is on the backend integration tests, not the frontend ones. This issue implied we had no integration tests which is not true since there were always **backend** integration tests. Just making sure those were being run for the OpenSearch distribution already.

**Comment by peterzhuamazon** [comment]
> My question is on the backend integration tests, not the frontend ones. This issue implied we had no integration tests which is not true since there were always **backend** integration tests. Just making sure those were being run for the OpenSearch distribution already.

BE integTest is there this issue is for dashboards.
I will change the title seems DB initial title is misleading.
Sorry and thanks.

**Comment by qreshi** [comment]
Got it, thanks Peter!
