### ISSUE TITLE
Extract dashboards-notifications and notifications onto separate repos

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#466]
**Is your feature request related to a problem?**

Coming from https://github.com/opensearch-project/opensearch-build/issues/2188, it's not possible to release and tag `notifications` separately from `dashboards-notifications` as, for example, `2.0.0`. This means we must release the two plugins at the same time.

**What solution would you like?**
The plugins should live in their own repos.

**What alternatives have you considered?**
A tagging scheme such as opensearch-2.0.0 vs. opensearch-dashboards-2.0.0.

**Comment by dblock** [comment]
See https://github.com/opensearch-project/opensearch-build/issues/2188#issuecomment-1259874232 in which we decided to split front-end and back-end components in v2.5.0.

**Comment by lezzago** [comment]
This has been completed
