### ISSUE TITLE
[FEATURE] Publish plugin zips to maven repo

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/notifications#474]
**Is your feature request related to a problem?**
With existing setup the plugin jars are only published to maven repo, but not the generated plugin zips.

#### Related META issue

https://github.com/opensearch-project/opensearch-build/issues/1916

**What solution would you like?**
A custom gradle plugin solution that can create the publication task for the zips to get published to local staging maven repo with right maven coordinates.
Add/Configure the custom gradle plugin openseearch.pluginzip to the gradle project and test the generated plugin zip's to upload to local maven repo.
More details on how to use the Plugin:
https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip

**Do you have any additional context?**
##### Current Behavior

Existing all maven publications target the jar files to publish to maven, but not the generated distribution zips.

##### Expected Behavior

Along with plugin jars, plugin zips should also be published to maven repo with right maven coordinates, so user can download these plugins using dependancy model.

**Comment by prudhvigodithi** [comment]
Hey @praveensameneni @lezzago can you please check this?
Thank you 
@bbarani

**Comment by bbarani** [comment]
@praveensameneni @lezzago Any updates on publishing notifications plugin zips to maven repo? This is the only plugin not published to Maven at this point in time and blocking us from closing out the Meta issue as well. @CEHENKLE
