### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/notifications#481]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @qreshi can you please post an update and make the necessary changes to align with core branching strategy.
Thank you
@dblock @CEHENKLE @bbarani

**Comment by qreshi** [comment]
I was blocked on Common Utils before. I'll proceed with updating Notifications now.

**Comment by qreshi** [comment]
Upgrading `main` to `3.0` is currently blocked on https://github.com/opensearch-project/OpenSearch/issues/3615

**Comment by qreshi** [comment]
Since the issue linked above is still ongoing and we can't upgrade to `3.0` on `main`, I'll update the version tag for this issue for tracking. I'd like to make sure `main` is on the most up-to-date development version before closing this issue out.

**Comment by lezzago** [comment]
Current blockers:
https://github.com/opensearch-project/opensearch-build/issues/2886
https://github.com/opensearch-project/opensearch-build/issues/2868

**Comment by lezzago** [comment]
Above have been unblocked, but now Notification needs to be on 2.5. For that to occur, PA and Security needs to be [here](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.5.0/opensearch-2.5.0.yml)

**Comment by qreshi** [comment]
Closing as all branches are now up-to-date.
