### ISSUE TITLE
[BUG] Gradle task order cause publishzip plugin to change groupid too early

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/notifications#501]
We recently add publish zip plugin to notifications/core and notifications/notifications.
https://github.com/opensearch-project/notifications/blob/2.2/notifications/core/build.gradle#L23
https://github.com/opensearch-project/notifications/blob/2.2/notifications/core/build.gradle#L23

The problem being that the task of this plugin will trigger automatically no matter what task is being called.
And it will try to switch the groupid to `org.opensearch.plugin` permanently for plugin zips to be published on https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/

See code:
https://github.com/opensearch-project/OpenSearch/pull/3252/files#diff-2a5851da2408bbeb8733433421917f253614fffe49449da0dd315a15ed8cdf74R43

------

This is not a problem if we only have 1-2 layers of gradle dependencies.
However, notifications plugin repository structure is set in a way that:
1. repo name notifications
2. within repo root, there is another notifications folder for backend plugin, with root build.gradle.
3. notifications/core and notifications/notifications have their own build.gradle which is called by the root build.gradle, and this is where the pluginzip publishing plugin is applied.

When running publish to maven local:
```
./gradlew publishToMavenLocal '-PexcludeTests=**/SesChannelIT*' -Dopensearch.version=2.2.0-SNAPSHOT -Dbuild.snapshot=true
```

The publishzip task goes before the publishmavenlocal task and switch the groupid from `org.opensearch` to `org.opensearch.plugin` way too early.

https://build.ci.opensearch.org/job/distribution-build-opensearch/5891/execution/node/240/log/
```
Caused by: org.gradle.api.publish.maven.InvalidMavenPublicationException: Invalid publication 'nebula': supplied groupId (org.opensearch) does not match value from POM file (org.opensearch.plugin). Cannot edit groupId directly in the POM file.
```

------

We currently have a temp fix in this PR: https://github.com/opensearch-project/opensearch-build/pull/2431

It will comment out/disable apply publishzip plugin before publishtomavenlocal, then revert back so that publishzip can run after the mavenlocal task.

Thanks.

**Comment by peterzhuamazon** [comment]
@prudhvigodithi @qreshi @lezzago

**Comment by prudhvigodithi** [comment]
Keeping this open from comment added by @lukas-vlcek https://github.com/opensearch-project/notifications/pull/554#issuecomment-1282280470.

**Comment by jmazanec15** [comment]
@prudhvigodithi @lukas-vlcek Running into a similar issue https://github.com/opensearch-project/neural-search/issues/31. If we are setting groupId to "org.opensearch.plugin" for publishing, why can't we set it for the project group? This seemed to fix my issue here: https://github.com/opensearch-project/k-NN/pull/596

**Comment by cwperks** [comment]
@prudhvigodithi @vibrantvarun and I are hitting this issue trying to fix https://github.com/opensearch-project/job-scheduler/issues/374 too. I have also noticed this now on security repo trying to do `./gradlew publishToMavenLocal`. Having different coordinates for the zip `org.opensearch.plugin` vs the jars `org.opensearch` is causing the issue. @vibrantvarun and I have been trying to add maven publications for both packaging types. i.e.

```
publishing {
    publications {
        pluginJar(MavenPublication){
            pom {
                name = "opensearch-job-scheduler"
                description = "OpenSearch Job Scheduler plugin"
                packaging = "jar"
                groupId = "org.opensearch"
            }
        }
        pluginZip(MavenPublication) {
            pom {
                name = "opensearch-job-scheduler"
                description = "OpenSearch Job Scheduler plugin"
                groupId = "org.opensearch.plugin"
            }
        }
    }
    repositories {
        maven {
            name = "Snapshots" //  optional target repository name
            url = "${rootDir}/snapshots"
        }
    }
}
```

and even with the `startParam.excludedTaskNames` set to exclude running plugin zip it still picks up the groupId defined in that pom section of the publication. The workaround that worked for this issue in notifications is not working for JS: https://github.com/opensearch-project/notifications/pull/554
