### ISSUE TITLE
[BUG] Opensearch dashboards notifications plugin on docker does not work

### ISSUE THREAD

**Issue by joriham** [opensearch-project/notifications#505]
**Describe the bug**

(this ticket was transferred from Opensearch to Dashboards, but I cannot see the original via search this ticket so I recreated)

After creating a channel and alarms etc to my belief by the book nothing works. This is a docker version of open search + dashboards and dockerhub official repo.

I've a webhook and email configuration, both fails timeout 30000ms error on GUI.

When I exec bash at container, I can use CURL to send webhook call to MS TEAMS generated webhook and get alert in the MS Teams channel. It proves that container => Internet => MS TEAMS is perfectly working, so IMO it must be something in the code.

With TCPDUMP I cannot see anything going out from container.

Logs are attached to end..

**To Reproduce**
0. Use Docker version of Open-search dashboards, I don't know if problem is with non-docker version.
1. Go to "Opensearch plugins / notifications"
2. Click on "Create channel"
3. Create Webhook-type channel to a valid webhook, for example Teams
4. Press "Send test message"
5. See the error after 30s

![image](https://user-images.githubusercontent.com/90329114/184835195-4a050f16-4d37-4708-8573-4df7b6a505dc.png)

After "Send test message"

![image](https://user-images.githubusercontent.com/90329114/184835317-026281b4-2d0c-4099-8a6e-d37cd64e0ffa.png)
![image](https://user-images.githubusercontent.com/90329114/184835359-1ff9660b-987f-47db-ab46-b9f23ef783a2.png)

After second send
![image](https://user-images.githubusercontent.com/90329114/184835554-395aa5ae-e1cc-49b9-b286-68a5ec901b28.png)

**Expected behavior**
Well Webhook (and email) should work so Teams channel should have test message and email too if email out is tested.

**OpenSearch Version**
Not relevant but docker pull'd same time as Dashboards with "latest"-tag

**Dashboards Version**
            "Labels": {
                "org.label-schema.build-date": "2022-06-30T22:04:43Z",
                "org.label-schema.description": "4011",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "opensearch-dashboards",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://opensearch.org",
                "org.label-schema.vcs-url": "https://github.com/opensearch-project/OpenSearch-Dashboards",
                "org.label-schema.vendor": "Amazon",
                "org.label-schema.version": "2.1.0"

**Plugins**

$ bin/opensearch-dashboards-plugin list
alertingDashboards@2.1.0.0
anomalyDetectionDashboards@2.1.0.0
ganttChartDashboards@2.1.0.0
indexManagementDashboards@2.1.0.0
notificationsDashboards@2.1.0.0
observabilityDashboards@2.1.0.0
queryWorkbenchDashboards@2.1.0.0
reportsDashboards@2.1.0.0
securityDashboards@2.1.0.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: docker on Ubuntu 22.04.4 LTS

**Additional context**

Logs
`
{"type":"error","@timestamp":"2022-08-16T08:33:52Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:143:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:97:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:92:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:164:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"http://xxx.yyy.hosting.fi/api/notifications/test_message/1NzJpYIBCI5M2_14qImg","message":"Internal Server Error"}
{"type":"response","@timestamp":"2022-08-16T08:33:52Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/notifications/test_message/1NzJpYIBCI5M2_14qImg","method":"get","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":500,"responseTime":22730,"contentLength":9},"message":"GET /api/notifications/test_message/1NzJpYIBCI5M2_14qImg 500 22730ms - 9.0B"}
{"type":"response","@timestamp":"2022-08-16T08:34:15Z","tags":[],"pid":1,"method":"delete","statusCode":200,"req":{"url":"/api/notifications/delete_configs?config_id_list=1NzJpYIBCI5M2_14qImg","method":"delete","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://xxx.yyy.hosting.fi","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":200,"responseTime":14,"contentLength":9},"message":"DELETE /api/notifications/delete_configs?config_id_list=1NzJpYIBCI5M2_14qImg 200 14ms - 9.0B"}
{"type":"response","@timestamp":"2022-08-16T08:34:59Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/notifications/create_config","method":"post","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","content-length":"441","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://xxx.yyy.hosting.fi","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":200,"responseTime":21,"contentLength":9},"message":"POST /api/notifications/create_config 200 21ms - 9.0B"}
{"type":"error","@timestamp":"2022-08-16T08:34:59Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:143:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:97:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:92:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:164:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"http://xxx.yyy.hosting.fi/api/notifications/test_message/1dzKpYIBCI5M2_14rolN","message":"Internal Server Error"}
{"type":"response","@timestamp":"2022-08-16T08:34:59Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/notifications/test_message/1dzKpYIBCI5M2_14rolN","method":"get","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":500,"responseTime":30011,"contentLength":9},"message":"GET /api/notifications/test_message/1dzKpYIBCI5M2_14rolN 500 30011ms - 9.0B"}
{"type":"response","@timestamp":"2022-08-16T08:35:29Z","tags":[],"pid":1,"method":"delete","statusCode":200,"req":{"url":"/api/notifications/delete_configs?config_id_list=1dzKpYIBCI5M2_14rolN","method":"delete","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://xxx.yyy.hosting.fi","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":200,"responseTime":23,"contentLength":9},"message":"DELETE /api/notifications/delete_configs?config_id_list=1dzKpYIBCI5M2_14rolN 200 23ms - 9.0B"}

`

**Comment by joriham** [comment]
Now I found my earlier bug report, so #504 and #505 are the same issue..

But anybody here? How to debug this issue?

**Comment by qreshi** [comment]
Hi @joriham, this may be related to https://github.com/opensearch-project/notifications/issues/343.

Unfortunately, the SendTestMessage is only formatting the body as plaintext today so when the payload expects a JSON format, the test message may fail. That doesn't mean the channel doesn't necessarily work though. Could you try to actually use the channel after creating it with something (for example, Alerting or IM)? Just so we can confirm this is in fact the issue.

**Comment by joriham** [comment]
@qreshi  - I'll take a look at #343 

This is the outcome of my test. I formulated Trigger-Action error message as JSON as I understood that was part of the request and previous experiment with standard text proposed by Dashboard plugin did not work. And on webhook  there is mandatory content-type json-header for 

Error message from UI as ASCII..
`
Error: Failed running action: org.opensearch.OpenSearchStatusException: {"event_status_list": [{"config_id":"GzORJIEB1zY3DXSy2drU","config_type":"webhook","config_name":"teams channel webhook","email_recipient_status":[],"delivery_status":{"status_code":"500","status_text":"Failed to send webhook message inmicsnebula.webhook.office.com"}}]}
`

Alerting status:
![image](https://user-images.githubusercontent.com/90329114/188076992-20dc683d-cbef-46aa-beb0-448f3b52d54f.png)
![image](https://user-images.githubusercontent.com/90329114/188077041-10ebd346-c1ef-410f-bdeb-73332e73e030.png)

configuration:
![image](https://user-images.githubusercontent.com/90329114/188077172-9296f642-949b-454a-9c3b-cb52942715eb.png)
![image](https://user-images.githubusercontent.com/90329114/188077217-6e9fc1e5-ae30-470f-8a98-da3590aaba1c.png)
![image](https://user-images.githubusercontent.com/90329114/188077310-95c48187-9b46-4279-bc63-c846b60b9325.png)

**Comment by joriham** [comment]
Then to add that webhook URL from Opensearch dashboards container with above config is all fine by curl CLI command..
![image](https://user-images.githubusercontent.com/90329114/188085982-871776ab-d68d-45f5-9284-fb09fdb1740b.png)
![image](https://user-images.githubusercontent.com/90329114/188086044-4ff10025-b1f7-47b2-9c73-bcfe1d499732.png)

**Comment by qreshi** [comment]
Would you be able to look at the `opensearch.log` so we can see what kind of payload is being sent for the notification? Or perhaps there will be more insight in the full stack trace there.

**Comment by qreshi** [comment]
I recall that the Mustache template in Alerting has had trouble guaranteeing valid JSON in the past (since Mustache itself doesn't really guarantee it). So if we can check that,  it might help in verifying the issue.

**Comment by joriham** [comment]
Let's add logs from container aka Opensearch.log as I understand it:

`[2022-09-14T14:11:09,240][INFO ][o.o.n.i.ConfigIndexingActions] [muro-mongodb-hel-2] notifications:NotificationConfig-get org.opensearch.commons.notifications.action.GetNotificationConfigRequest@5cdbf60a
[2022-09-14T14:11:09,240][INFO ][o.o.n.i.ConfigIndexingActions] [muro-mongodb-hel-2] notifications:NotificationConfig-info GzORJIEB1zY3DXSy2drU
[2022-09-14T14:11:09,241][INFO ][o.o.n.s.SendMessageActionHelper] [muro-mongodb-hel-2] notifications:getSingleConfig-get GzORJIEB1zY3DXSy2drU
[2022-09-14T14:11:09,401][ERROR][o.o.n.c.t.WebhookDestinationTransport] [muro-mongodb-hel-2] Exception sending webhook message GzORJIEB1zY3DXSy2drU: org.opensearch.notifications.spi.model.MessageContent@2d8e87be
java.io.IOException: Failed: Summary or Text is required.
        at org.opensearch.notifications.core.client.DestinationHttpClient.validateResponseStatus(DestinationHttpClient.kt:150) ~[opensearch-notifications-core-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.core.client.DestinationHttpClient.execute(DestinationHttpClient.kt:98) ~[opensearch-notifications-core-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.core.transport.WebhookDestinationTransport.sendMessage(WebhookDestinationTransport.kt:41) [opensearch-notifications-core-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.core.transport.WebhookDestinationTransport.sendMessage(WebhookDestinationTransport.kt:21) [opensearch-notifications-core-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage$lambda-0(NotificationCoreImpl.kt:38) [opensearch-notifications-core-2.1.0.0.jar:2.1.0.0]
        at java.security.AccessController.doPrivileged(AccessController.java:318) [?:?]
        at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage(NotificationCoreImpl.kt:35) [opensearch-notifications-core-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.send.SendMessageActionHelper.sendMessageThroughSpi(SendMessageActionHelper.kt:574) [opensearch-notifications-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.send.SendMessageActionHelper.sendWebhookMessage(SendMessageActionHelper.kt:398) [opensearch-notifications-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.send.SendMessageActionHelper.sendMessageToChannel(SendMessageActionHelper.kt:229) [opensearch-notifications-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.send.SendMessageActionHelper.access$sendMessageToChannel(SendMessageActionHelper.kt:61) [opensearch-notifications-2.1.0.0.jar:2.1.0.0]
        at org.opensearch.notifications.send.SendMessageActionHelper$sendMessagesInParallel$1$statusDeferredList$1$1.invokeSuspend(SendMessageActionHelper.kt:157) [opensearch-notifications-2.1.0.0.jar:2.1.0.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.10.jar:1.6.10-release-923(1.6.10)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
[2022-09-14T14:11:09,401][INFO ][o.o.n.s.SendMessageActionHelper] [muro-mongodb-hel-2] notifications:sendMessage:statusCode=500, statusText=Failed to send webhook message Failed: Summary or Text is required.
[2022-09-14T14:11:09,402][WARN ][o.o.n.a.PluginBaseAction ] [muro-mongodb-hel-2] notifications:OpenSearchStatusException:
org.opensearch.OpenSearchStatusException: {"event_status_list": [{"config_id":"GzORJIEB1zY3DXSy2drU","config_type":"webhook","config_name":"teams channel webhook","email_recipient_status":[],"delivery_status":{"status_code":"500","status_text":"Failed to send webhook message Failed: Summary or Text is required."}}]}
        at org.opensearch.notifications.send.SendMessageActionHelper.executeRequest(SendMessageActionHelper.kt:99) ~[?:?]
        at org.opensearch.notifications.send.SendMessageActionHelper$executeRequest$1.invokeSuspend(SendMessageActionHelper.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.10.jar:1.6.10-release-923(1.6.10)]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.6.10.jar:1.6.10-release-923(1.6.10)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
`

**Comment by joriham** [comment]
Is this error related:
[https://forum.opensearch.org/t/mustache-template-function-removing-trailing-comma/2528](url)

> What do we do when dealing with JSON object on webhooks? Current templating with aggregations basically makes it impossible due to trailing commas.

> For example, using any kind of templating requires iterations over an object in the ES response object. However, every json iteration that will be seperated by a comma will always have a trailing comma like so:

{
  "obj1": "val1",
  "obj2": "val2",
  "obj3": "val3",
  "obj4": "val4", <- Sadface
}
> The vast majority of JSON compliant webhooks will reject this / fail to decode the JSON object on the other end.

> Any suggestions on how to get around this?

There was some suggestion:
{{#toJson}}ctx.results.0{{/toJson}}

but I did not succees that, tried foo as text and json object "foo": "bar"

**Comment by joriham** [comment]
I was experimenting custom webhook URL which if forwarded to netcat:

Pressing send test message with
![image](https://user-images.githubusercontent.com/90329114/190407701-182fda4c-6b78-49a9-8cf0-26eb2116dccb.png)

Gave correct looking output
![image](https://user-images.githubusercontent.com/90329114/190407660-62b4e4ad-d91f-4dee-809e-13d1518950f6.png)

so I added it to test monitor with more identifiers and enabled it and got:
![image](https://user-images.githubusercontent.com/90329114/190408739-a34a99e5-f890-4e03-90bd-2864160d3599.png)

To me it looks fine..

**Comment by joriham** [comment]
Ok, my test string was bad for Teams API as on JSON it expects Office 365 connector card -format.
