### ISSUE TITLE
 Re-enable detekt when snakeyaml vulnerability is fixed 

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#529]
Is your feature request related to a problem?
All of the snakeyaml versions are currently vulnerable. detekt depends on snakeyaml.
So, detekt is disabled for now until snakeyaml vulnerability is fixed. https://github.com/opensearch-project/notifications/pull/528

this issue is created to track the progress of re-enabling detekt when snakeyaml vulnerability is fixed.

**Comment by SuZhou-Joe** [comment]
Add more detail.

**Comment by Hailong-am** [comment]
we need bump `io.gitlab.arturbosch.detekt:detekt-gradle-plugin` version to `1.23.0` based on compatibility matrix of detekt https://detekt.dev/docs/introduction/compatibility/

**Comment by Noir01** [comment]
All that needs to be done is undo the changes of #528 while bumping the version to 1.23.0, right?

Can I be assigned to this?
