### ISSUE TITLE
[BUG] - Multi tenant support when using security + notifications plugin

### ISSUE THREAD

**Issue by amit-cloudinary** [opensearch-project/notifications#577]
**What is the bug?**
When configuring a new notification within a specific tenant , the notification is visible to all other tenants .
this breaks the multi tenant isolation ?

**How can one reproduce the bug?**
1. Go to notifications under a specific tenant
2. Create a new notification (for example slack)
3. then login as another user in another tenant
4.you will see the notification of the previous tenant

**What is the expected behavior?**
i would expect that notification created under a specific tenant be visible only to that tenant and only global notification visible to all

 - Plugins - security, notifications

**Comment by lezzago** [comment]
The Notification plugin does not support multi-tenancy. Notification has something similar to that where there is more documentation here: https://opensearch.org/docs/latest/monitoring-plugins/alerting/security/#advanced-limit-access-by-backend-role.

To enable the setting for notification, it is here:
```
PUT _cluster/settings
{
  "persistent": {
    "opensearch.notifications.general.filter_by_backend_roles": "true"
  }
}
```
