### ISSUE TITLE
Remove jackson-databind and jackson-annotations dependencies now coming from core

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/notifications#579]
jackson-databind and jackson-annotations were added as api dependencies in `server` of opensearch core.  Therfore, all plugins now have these as transitive dependencies.  Plugins that currently consume these dependencies directly will break while building unless the direct dependencies are removed.  If your plugin does not consume jackson-databind or jackson-annotations directly, feel free to close the related issue in your plugin's repository.

Example of solution in security plugin: https://github.com/opensearch-project/security/pull/2325

**Comment by lezzago** [comment]
Need to remove the following:
- https://github.com/opensearch-project/notifications/blob/5b9ff98301f94478c0f2180ccd08abac09049491/notifications/core/build.gradle#L111-L112
- https://github.com/opensearch-project/notifications/blob/5b9ff98301f94478c0f2180ccd08abac09049491/notifications/notifications/build.gradle#L97-L98
- https://github.com/opensearch-project/notifications/blob/5b9ff98301f94478c0f2180ccd08abac09049491/notifications/core-spi/build.gradle#L86-L87
