### ISSUE TITLE
[BUG] The default size limit for email is too small and not consistent with the code

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/notifications#658]
**What is the bug?**
User encounters an [Email size larger than 10000](https://forum.opensearch.org/t/email-size-larger-than-10000/13998) error when sending email by notification plugin, it seems that the default size limit 10000 is too small, and it's configured here: 
[notification-core.yml](https://github.com/opensearch-project/notifications/blob/main/notifications/core/src/main/config/notifications-core.yml), but found that the default value is [10000000 in the code](https://github.com/opensearch-project/notifications/blob/6d7951eb8035516dafc46c7783a3f98f4f98a1be/notifications/core/src/main/kotlin/org/opensearch/notifications/core/setting/PluginSettings.kt#L111), which is confused.
**How can one reproduce the bug?**
1. Get cluster settings
```
GET _cluster/settings?include_defaults=true
```
, you can see the default settings below:

```
"email": {
            "minimum_header_length": "100",
            "size_limit": "10000"
          }
```

**What is the expected behavior?**
Modify the default value for the setting `email.size_limit` and `email.minimum_header_length` in the bindle file [notification-core.yml](https://github.com/opensearch-project/notifications/blob/main/notifications/core/src/main/config/notifications-core.yml), make them consistent with the default value in the code.

**What is your host/environment?**
 - OS: [Mac]
 - Version [2.6.0]

**Comment by gaobinlong** [comment]
@zhongnansu it seems that you were doing some related work before, could you help to get us understand why the default value of max size limit and minimum header length for email are not consistent with the code? Thanks!

**Comment by zhongnansu** [comment]
> @zhongnansu it seems that you were doing some related work before, could you help to get us understand why the default value of max size limit and minimum header length for email are not consistent with the code? Thanks!

@gaobinlong I think the value mismatch is a typo/bug, we should correct it in `notification-core.yml`

**Comment by gaobinlong** [comment]
Close this issue as the fix PR has been merged yet, thanks @zhongnansu.
