### ISSUE TITLE
[BUG] Some slf4j warn message shows in the log file when sending email

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/notifications#693]
**What is the bug?**
When sending a email at the first time, OpenSearch main log shows that there are some slf4j related warn message, I think it should be eliminated:
```
[2023-06-26T17:02:40,596][WARN ][stderr                   ] [bcd07466ee01] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2023-06-26T17:02:40,597][WARN ][stderr                   ] [bcd07466ee01] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2023-06-26T17:02:40,597][WARN ][stderr                   ] [bcd07466ee01] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**How can one reproduce the bug?**
1. Go to 'Alerting plugin of OSD '
2. Click on 'send test message' after you have setup email account correctly and creating a alerting monitor
3. See some warn log in OpenSearch main log file

**What is the expected behavior?**
Remove the unexpected warn log

**What is your host/environment?**
 - OS: [MacOS]
 - Version [3.0]
 - Plugins: notification, alerting

**Do you have any screenshots?**
<img width="1211" alt="image" src="https://github.com/opensearch-project/notifications/assets/15811131/4fdcfa1c-3d04-4c3d-8a97-e20775ace50e">

**Comment by Noir01** [comment]
Hi! I'll try my best to fix the bug.

**Comment by Hailong-am** [comment]
trying to reproduce in my local. when i try with slack webhook, there also have same waring message printed in console.

**Comment by Hailong-am** [comment]
@Noir01 @gaobinlong  Add `implementation "org.apache.logging.log4j:log4j-slf4j-impl:${versions.log4j}"` to `core/build.gradle` dependencies will solve the issue
