### ISSUE TITLE
Improve security-notifications-test-workflow.yml workflow for security plugin enabling check

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/notifications#727]
If security plugins is not installed, endpoint `https://localhost:9200` is not accessible. In this case, the way we determine security is enabled or not is not valid. 
```shell
cluster_running=`curl -XGET https://localhost:9200/_cat/plugins -u admin:admin --insecure`
echo $cluster_running
security=`curl -XGET https://localhost:9200/_cat/plugins -u admin:admin --insecure |grep opensearch-security|wc -l`
echo $security
if [ $security -gt 0 ]
```

Here is an alternative 
```shell
container_id=`docker ps -q`
security =`docker exec $container_id /usr/share/opensearch/bin/opensearch-plugin list | grep opensearch-security | wc -l`
```
 

[1] https://github.com/opensearch-project/notifications/blob/main/.github/workflows/security-notifications-test-workflow.yml

**Comment by xluo-aws** [comment]
Should we use the same as what FTrepo used? curl http://localhost:5601/api/status -u admin:admin --insecure
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/workflows/release-e2e-workflow-template.yml 

It works no matter docker is used or not.

**Comment by Hailong-am** [comment]
> Should we use the same as what FTrepo used? curl http://localhost:5601/api/status -u admin:admin --insecure https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/workflows/release-e2e-workflow-template.yml
> 
> It works no matter docker is used or not.

It use tar ball, it should have similar issue. If security plugin was not installed, endpoint `https://localhost:9200` is not accessable
