### ISSUE TITLE
[BUG]org.opensearch.integtest.config.ChimeNotificationConfigCrudIT failed when running integration tests with OpenSearch rpm/deb package

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/notifications#783]
**What is the bug?**

There's an [integration test failure](https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/6332/pipeline/123) when running tests with OpenSearch rpm/deb package, it seems that we do not handle the warnings correctly when calling `_refresh` API:

```
Warnings: [this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default, this request accesses system indices: [.opensearch-notifications-config], but in a future major version, direct access to system indices will be prevented by default]
```
, we need to dive deep on this and fix it.

**What is the expected behavior?**
Integration tests runs successfully with rpm/deb package.

**Do you have any screenshots?**
<img width="1760" alt="截屏2023-10-11 16 42 01" src="https://github.com/opensearch-project/notifications/assets/15811131/57895c44-d374-41bd-9a90-2da5735f1f6b">

**Comment by bbarani** [comment]
[integ-test-failure](https://github.com/opensearch-project/notifications/labels/integ-test-failure) is reserved for the bot. Please use a different label to track integration failures.
