### ISSUE TITLE
Add webhook format check for Slack

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/notifications#787]
Add Slack webhook URL format check here 
https://github.com/opensearch-project/notifications/blob/main/notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/ConfigIndexingActions.kt#L59

it should have same url format check as Microsoft teams

**Comment by zhichao-aws** [comment]
If we change this validation, we need to modify UT/IT in this repo, as well as in dashboards-notifications. The mock data doesn't have the correct format, and this will fail dashboards-notifications cypress test

**Comment by Noir01** [comment]
Can I be assigned to this, seeing how bblazek98 doesn't seem to be interested?

**Comment by SuZhou-Joe** [comment]
> Can I be assigned to this, seeing how bblazek98 doesn't seem to be interested?

Sure, assigned.
