### ISSUE TITLE
Add Chime webhook URL format check

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/notifications#788]
Add Chime webhook URL format check here
https://github.com/opensearch-project/notifications/blob/main/notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/ConfigIndexingActions.kt#L64

it should have same url format check as Microsoft teams

**Comment by bblazek98** [comment]
Hello, could i be assigned to this issue?

**Comment by Hailong-am** [comment]
> Hello, could i be assigned to this issue?

assigned

**Comment by Noir01** [comment]
Since I'm also assigned to #787 and nearly done with it, can I be assigned to this?

**Comment by Hailong-am** [comment]
@bblazek98 Do you have chance to working this? otherwise, we can reassign it to @Noir01

**Comment by Noir01** [comment]
I don't think @bblazek98 is going to respond.

**Comment by Hailong-am** [comment]
> I don't think @bblazek98 is going to respond.

reassign to @Noir01
