### ISSUE TITLE
Replace TestMailServer with GreenMail for email destination unit test

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/notifications#789]
TestMailServer is deprecated, we need to switch to GreenMail for email unit test

https://github.com/opensearch-project/notifications/blob/main/notifications/core/src/test/kotlin/org/opensearch/notifications/core/smtp/SmtpEmailTests.kt#L24

**Comment by rachana-dani** [comment]
Can this be assigned to me?

**Comment by rachana-dani** [comment]
If this is not already picked by someone? @Hailong-am

**Comment by zhichao-aws** [comment]
close as completed
