### ISSUE TITLE
[BUG] - Can't select Channel notification

### ISSUE THREAD

**Issue by ggt** [opensearch-project/notifications#922]
After a lot of updates, i have an issue with the latest 2.14.0, i can't select notification i get a 400 error.
Channels are visible in channel tab.

I give you some screenshots.

-- EDIT --
I found the error, you must add this parameter and make a loop between config_type in this query :+1: [/api/notifications/get_configs?from_index=0&max_items=5000&sort_field=name&sort_order=asc&**config_type=webhook**](https://127.0.0.1:5601/api/notifications/get_configs?from_index=0&max_items=10&query=&config_type=slack&config_type=email&config_type=chime&config_type=microsoft_teams&config_type=webhook&config_type=sns&sort_field=name&sort_order=asc)

![image](https://github.com/opensearch-project/notifications/assets/941924/8445eb4d-5ae5-42dc-8aa4-e8677352ddd1)

![image](https://github.com/opensearch-project/notifications/assets/941924/1a3e1f73-8e9c-448b-8873-e930e089028e)
![image](https://github.com/opensearch-project/notifications/assets/941924/e955d606-02b1-4eaa-91c4-1ade7d963dcd)

**Comment by ggt** [comment]
I give you some other screenshots
![image](https://github.com/opensearch-project/notifications/assets/941924/bb82fbd0-ce5d-427a-a19c-70bdcc8c074e)
![image](https://github.com/opensearch-project/notifications/assets/941924/4c09cddc-c875-446a-af5c-5510dba191ba)

**Comment by ggt** [comment]
it works when i rewrite url from https://127.0.0.1:5601/api/notifications/get_configs?from_index=0&max_items=5000&sort_field=name&sort_order=asc -> https://127.0.0.1:5601/api/notifications/get_configs?from_index=0&max_items=10&query=&config_type=slack&config_type=email&config_type=chime&config_type=microsoft_teams&config_type=webhook&config_type=sns&sort_field=name&sort_order=asc
![image](https://github.com/opensearch-project/notifications/assets/941924/90877985-0ae9-4e59-ab04-8b5ca7240c8a)

**Comment by shamil** [comment]
We are experiencing same issue, is this somethign that will be fixed?

**Comment by dblock** [comment]
Doesn't look like anyone has looked at this. Maybe you can help?

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by ullgren** [comment]
I see the same bug with 2.14.0

**Comment by Hailong-am** [comment]
It has been fixed in 2.15, see https://github.com/opensearch-project/alerting-dashboards-plugin/issues/961 as reference.
